name: Build and deploy FastAPI app to Azure Web App - tech0-gen8-step4-pos-app-80

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify repository contents
        run: ls -R  # すべてのファイルを表示

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Check requirements.txt location
        run: |
          if [ ! -f pos-app-back/app/requirements.txt ]; then
            echo "❌ requirements.txt が見つかりません！"
            exit 1
          else
            echo "✅ requirements.txt を確認しました"
          fi

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r pos-app-back/app/requirements.txt

      - name: Zip artifact for deployment
        run: zip -r release.zip ./

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: fastapi-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: fastapi-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'tech0-gen8-step4-pos-app-80'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_DEBFE78FBB0C44F093342F38FFED56FD }}
